### ISSUE TITLE
Suggestion for /preparation.md: A note about installing Kali in Virtualbox

### ISSUE THREAD

**Issue by nickleus** [chryzsh/practical-hacking#1]
Under Goal 3,
Maybe give users a note about how to install the Kali ova file, e.g. in Virtualbox?

> After downloading the Kali ova file, here's how you install it in VirtualBox:
> **File > Import Appliance > _Select the Kali ova file you downloaded_ > Import**

**Comment by chryzsh** [comment]
Wrote this for Virtualbox and VMWare workstation. Thanks for the contribution. Commit: https://github.com/chryzsh/practical-hacking/commit/00dc41ae964eb7b9b67b0b09e2f599a2c9cc40cf
